/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

import org.junit.Test;

import jdk.jfr.Timestamp;

import org.junit.After;
import org.junit.Before;
import static org.junit.Assert.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

public class BallTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final PrintStream originalOut = System.out;

    @Before
    public void setUpStreams () {
        System.setOut(new PrintStream(outContent));
    }

    @After
    public void restoreStreams () {
        outContent.reset();
        System.setOut(originalOut);
    }

    @Test
    public void testDogBarkMethod() {
        Dog dog = new Dog();
        dog.bark();
        assertEquals(outContent.toString(), "bark bark");
        Ball ball = new Ball();
        Ball ball1 = new Ball(1.0, 2.0);
        Ball ball2 = new Ball(5.0, 10.0, 7.0, "green");
        assertEquals(ball.printInfo(), "x: 0.0 y: 0.0 v: 0.0 r: 10.0 color: white");
        assertEquals(ball1.printInfo(), "x: 1.0 y: 2.0 v: 0.0 r: 10.0 color: white");
        assertEquals(ball2.printInfo(), "x: 5.0 y: 10.0 v: 0.0 r: 7.0 color: green");
    }
}
