/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

import org.junit.Test;

// import jdk.jfr.Timestamp;

import org.junit.After;
import org.junit.Before;
import static org.junit.Assert.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

public class CircleTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final PrintStream originalOut = System.out;

    @Before
    public void setUpStreams () {
        System.setOut(new PrintStream(outContent));
    }

    @After
    public void restoreStreams () {
        outContent.reset();
        System.setOut(originalOut);
    }

    @Test
    public void testConstructor () {
        Circle c = new Circle();
        assertEquals(c.toString(), "black circle, r = 5.0");
    }

    @Test
    public void testGetR () {
        Circle c = new Circle();
        assertEquals(c.getR(), 5.0, 0.1);
    }

    @Test
    public void testGetP () {
        Circle c = new Circle();
        assertEquals(c.getP(), 2 * 5 * Math.PI, 0.01);
    }

    @Test
    public void testGetS () {
        Circle c = new Circle();
        assertEquals(c.getS(), 78.53981, 0.001);
    }
}
