/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

import org.junit.Test;
import static org.junit.Assert.*;

public class DogTest {
    @Test public void testDogBarkMethod() {
        Dog dog = new Dog();
        assertEquals(dog.bark(), "bark bark");
    }
}
