/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

import org.junit.Test;

import org.junit.After;
import org.junit.Before;
import static org.junit.Assert.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

public class HumanTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final PrintStream originalOut = System.out;

    @Before
    public void setUpStreams () {
        System.setOut(new PrintStream(outContent));
    }

    @After
    public void restoreStreams () {
        outContent.reset();
        System.setOut(originalOut);
    }


    /**
     * Tests
     */
    @Test
    public void testHumanConstructor () {
        Human human = new Human();
        assertEquals(human.toString(), "Vasya; height: 170.0; weight: 70.0");
    }

    @Test
    public void testNameMethods () {
        Human human = new Human();
        human.setName("Petya");
        assertEquals(human.getName(), "Petya");
        assertEquals(human.toString(), "Petya; height: 170.0; weight: 70.0");
    }

    @Test
    public void testPartsOfBodyMethods () {
        Human human = new Human();

        human.core.setLength(80.0);
        human.leftLeg.setLength(75.0);
        human.rightLeg.setLength(75.0);

        assertEquals(human.getHeight(), 185, 0.01);

        human.core.setWeight(51.0);

        assertEquals(human.getWeight(), 90, 0.01);
    }
}
