/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

import java.util.Stack;

public class DogPlace {
    private Stack<Dog> place;

    public DogPlace () {
        place = new Stack<>();
    }

    public void add (Dog dog) {
            place.push(dog);
            System.out.println(place);
    }
}
