/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

import org.junit.Test;

import org.junit.After;
import org.junit.Before;
import static org.junit.Assert.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

public class BookTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final PrintStream originalOut = System.out;

    @Before
    public void setUpStreams () {
        System.setOut(new PrintStream(outContent));
    }

    @After
    public void restoreStreams () {
        outContent.reset();
        System.setOut(originalOut);
    }

    /**
     * Tests
     */
    @Test
    public void testBookConstructor () {
        Book book = new Book();
        assertEquals(book.toString(), "Book; author: Anonimus; 10 pages");

        Book book1 = new Book("Math", "Albert Einstein", 1325);
        assertEquals(book1.toString(), "Math; author: Albert Einstein; 1325 pages");
    }

    @Test
    public void testPagesMethods () {
        Book book = new Book();
        assertEquals(book.getCurrentPage(), 1);

        book.flip();
        assertEquals(book.flip(), 3);
        assertEquals(book.getCurrentPage(), 3);

        book.setCurrentPage(8);
        assertEquals(book.getCurrentPage(), 8);
    }
}
